version: '3.1'
services:
  node:
    image: node:18.15.0-alpine3.17
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "5173:5173"
    container_name: todolist_dev
    command: npm run dev-docker
